version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "competitor-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-d11ompem3hz5"
s3_prefix = "competitor-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
